spring:
  application:
    name: books
  cloud:
    aws:
      dynamodb:
        region: us-east-1
      credentials:
        access-key: local
        secret-key: local
      endpoint: http://localhost:4566
server:
  port: 8082
